# Generated by Django 3.2.21 on 2023-09-07 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20230906_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='renewal',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='years',
            field=models.IntegerField(default=0),
        ),
    ]
