# Generated by Django 3.2.21 on 2023-09-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20230907_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlineitem',
            name='years',
            field=models.IntegerField(default=0),
        ),
    ]
