# Generated by Django 3.2.21 on 2023-09-08 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20230908_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivery_cost',
            new_name='vat_cost',
        ),
    ]
