# Generated by Django 3.2.21 on 2023-09-11 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='enddate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='license_key',
            field=models.CharField(editable=False, max_length=32, null=True),
        ),
    ]
